import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisScroll from "./components/LenisScroll";

const bdoGrotesk = localFont({
  src: [
    {
      path: "../public/fonts/BDOGrotesk-Light-BF648a656f46f93.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/BDOGrotesk-Regular-BF648a656f74a27.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/BDOGrotesk-Medium-BF648a656f49882.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/BDOGrotesk-DemiBold-BF648a656f04a15.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/BDOGrotesk-Bold-BF648a656f312c4.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/BDOGrotesk-ExtraBold-BF648a656f31316.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/BDOGrotesk-Black-BF648a656e295cc.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-bdo-grotesk",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bdoGrotesk.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisScroll />
        {children}
      </body>
    </html>
  );
}
